### ISSUE TITLE
Timer1 initialization problem

### ISSUE THREAD

**Issue by jremington** [ahooper/WWVBClock#1]
Nice code, but version 7 (and possibly others) has a subtle error that leads to unacceptable drift in the 100 Hz sample period, relative to the WWVB transmitter.

This line of code is the problem:
  	OCR1A = F_CPU / 256 / SAMPLE_HZ;    // compare match register 16MHz / 256 prescaler / SAMPLE_HZ

This leads to a sample period that is 16 us too long, so that the sample loop goes rather rapidly out of sync with WWVB.  According to the processor data sheet, TOP should be set to 1 less, as follows:

  	OCR1A = F_CPU / 256 / SAMPLE_HZ - 1;    // compare match register 16MHz / 256 prescaler / SAMPLE_HZ - 1

I've corrected this in my version of the code, which (with an accurate 16 MHz crystal) tracks WWVB for hours without losing sync.

**Comment by ahooper** [comment]
Thanks for the detailed examination to discover this error!
